// Videos Data

export const videosData = [
  {
    video: require("../../storage/videos/vid1.mp4"),
    postProfile: require("../../storage/images/part1.jpg"),
    title: "Garv_Chouhan",
    description: "SunRise",
    likes: "240k",
    isLike: false,
  },
  {
    video: require("../../storage/videos/vid2.mp4"),
    postProfile: require("../../storage/images/part2.jpg"),
    title: "CleverQazi",
    description: "Physical Health",
    likes: "640k",
    isLike: false,
  },
  {
    video: require("../../storage/videos/vid3.mp4"),
    postProfile: require("../../storage/images/part3.jpg"),
    title: "Sugashaw",
    description: "RoadTrip",
    likes: "340k",
    isLike: false,
  },
  {
    video: require("../../storage/videos/vid4.mp4"),
    postProfile: require("../../storage/images/part4.jpg"),
    title: "Sunny_Sangha",
    description: "Nature",
    likes: "140k",
    isLike: false,
  },
  {
    video: require("../../storage/videos/vid5.mp4"),
    postProfile: require("../../storage/images/part5.jpg"),
    title: "Yash_Dubey",
    description: "Beach",
    likes: "450k",
    isLike: false,
  },
  {
    video: require("../../storage/videos/vid6.mp4"),
    postProfile: require("../../storage/images/part6.jpg"),
    title: "Astronut",
    description: "Fly just like astrounot",
    likes: "450k",
    isLike: false,
  },
];

export const friendProfile = [
  {
    name: "Gaurav_Chouhan",
    accountName: "Gaurav_C",
    profileImage: require("../../storage/images/part1.jpg"),
    posts: 36,
    followers: 6542,
    following: 43,
    follow: false,
  },
  {
    name: "Shivam",
    accountName: "Shivam_Devil",
    profileImage: require("../../storage/images/part2.jpg"),
    posts: 16,
    followers: 542,
    following: 3,
    follow: false,
  },
  {
    name: "Raj senger",
    accountName: "Raj_Senger",
    profileImage: require("../../storage/images/part3.jpg"),
    posts: 3,
    followers: 42,
    following: 3,
    follow: false,
  },
  {
    name: "Ravi Tanwer",
    accountName: "Ravi_Tanwer",
    profileImage: require("../../storage/images/part4.jpg"),
    posts: 7,
    followers: 342,
    following: 23,
    follow: false,
  },
  {
    name: "Garv Chouhan",
    accountName: "Garv_CHouhan",
    profileImage: require("../../storage/images/part5.jpg"),
    posts: 12,
    followers: 6542,
    following: 21,
    follow: false,
  },
  {
    name: "Shreya Thakur",
    accountName: "Shreya_Thakur",
    profileImage: require("../../storage/images/part6.jpg"),
    posts: 10,
    followers: 654298,
    following: 21,
    follow: false,
  },
  {
    name: "Shivani Namdev",
    accountName: "Shivani_Namdev",
    profileImage: require("../../storage/images/part7.jpg"),
    posts: 16,
    followers: 65445,
    following: 10,
    follow: false,
  },
  {
    name: "Priyanka Patidar",
    accountName: "Priyanka",
    profileImage: require("../../storage/images/part8.jpg"),
    posts: 26,
    followers: 2342,
    following: 13,
    follow: false,
  },
  {
    name: "Neha Prajapat",
    accountName: "neha_parajpat",
    profileImage: require("../../storage/images/part9.jpg"),
    posts: 10,
    followers: 6542345,
    following: 23,
    follow: false,
  },
  {
    name: "Chitra Patel",
    accountName: "Chitra_Patel",
    profileImage: require("../../storage/images/part10.jpg"),
    posts: 10,
    followers: 654,
    following: 10,
    follow: false,
  },
  {
    name: "Yash Chand",
    accountName: "Yash_C",
    profileImage: require("../../storage/images/part12.jpg"),
    posts: 110,
    followers: 654456,
    following: 100,
    follow: false,
  },
  {
    name: "Shivam Mandwal",
    accountName: "Shivam_manwal",
    profileImage: require("../../storage/images/part13.jpg"),
    posts: 30,
    followers: "1.5K",
    following: 100,
    follow: false,
  },
  {
    name: "__garv_5__",
    accountName: "Garv Chouhan",
    profileImage: require("../../storage/images/part14.jpg"),
    posts: 110,
    followers: "1.5M",
    following: 1,
    follow: false,
  },
  {
    name: "Nidhi Mishra",
    accountName: "Nidhi_mishra",
    profileImage: require("../../storage/images/part15.jpg"),
    posts: 20,
    followers: 6554,
    following: 1000,
    follow: false,
  },
  {
    name: "Shivani Rathud",
    accountName: "Shivani_Rathud",
    profileImage: require("../../storage/images/part11.jpg"),
    posts: 20,
    followers: 6545,
    following: 108,
    follow: false,
  },
];
